// Package adapters defines the contract between VichuFlow and the coding agents
// it orchestrates, plus the built-in implementations (claude-code, codex, shell,
// fake).
//
// Adapters are the project's frontier of fragility: agent CLIs change their
// flags and output formats, so all of that churn is isolated here and never
// leaks into the engine. Every adapter normalizes its native output into the
// shared AgentEvent stream and a core.Result.
package adapters

import (
	"context"

	"github.com/corteshvictor/vichu-flow/internal/core"
)

// Availability is the result of probing an adapter's backing tool.
type Availability struct {
	Name      string `json:"name"`
	Available bool   `json:"available"`
	Version   string `json:"version,omitempty"`
	Reason    string `json:"reason,omitempty"` // why unavailable, if not
}

// Caps declares what an adapter's backing tool can do, so the engine degrades
// gracefully instead of assuming capabilities.
type Caps struct {
	Streaming        bool `json:"streaming"`
	Resume           bool `json:"resume"`
	CostReporting    bool `json:"cost_reporting"`
	StructuredOutput bool `json:"structured_output"`
}

// Invocation is everything an adapter needs to run one worker. The engine
// builds it, prepending the project context pack to Prompt.
type Invocation struct {
	Role         string   // explorer, implementer, reviewer
	Prompt       string   // full prompt, context pack already prepended
	WorkDir      string   // repo root the agent operates in
	ContextPaths []string // files the worker should be aware of
	Model        string   // desired model, if the adapter supports it
	Effort       string   // reasoning effort hint
	// Iteration is the engine's 1-based entry count for this stage. It lets a
	// deterministic adapter (the fake) vary its output per engine iteration
	// (e.g. needs_fixes then approved) WITHOUT relying on adapter-internal state,
	// so it works even when the registry builds a fresh adapter per stage.
	Iteration int
	// ReadOnly marks a stage the worker must not modify the tree in (e.g. review).
	// Adapters that can sandbox enforce it BEFORE the fact — codex runs with
	// `--sandbox read-only`, claude-code denies its edit tools — rather than
	// letting the engine only detect a mutation after it happened.
	ReadOnly bool
	Command  []string // for the shell adapter: the command to run
	// AllowNonZeroExit makes the shell adapter treat a non-zero exit code as a
	// normal result instead of a worker failure.
	AllowNonZeroExit bool
	// DisallowedTools is generated by the security policy; adapters that
	// support tool permissions (claude-code) translate it natively.
	DisallowedTools []string
	Env             map[string]string // extra environment for the invocation
}

// AgentEvent is one normalized event from a running agent. Kind is one of the
// Event* constants below.
type AgentEvent struct {
	Kind   string
	Text   string
	Detail map[string]any
}

// Normalized agent event kinds.
const (
	EventToolUse = "tool_use"
	EventText    = "text"
	EventError   = "error"
	EventDone    = "done"
)

// Session is a running (or finished) agent invocation.
type Session interface {
	// Events streams normalized events until the agent finishes, then closes.
	Events() <-chan AgentEvent
	// Result blocks until the agent finishes and returns its outcome.
	Result(ctx context.Context) (core.Result, error)
	// Interrupt asks the agent to stop.
	Interrupt(ctx context.Context) error
}

// Adapter runs workers via a particular coding agent.
type Adapter interface {
	Name() string
	Probe(ctx context.Context) (Availability, error)
	Capabilities() Caps
	Start(ctx context.Context, inv Invocation) (Session, error)
	// Resume continues a prior session by id. Adapters that cannot resume should
	// declare Resume:false in Caps and return ErrResumeUnsupported.
	Resume(ctx context.Context, sessionID string, inv Invocation) (Session, error)
}
